// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecurityProject.API.Data;

namespace SecurityProject.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("SecurityProject.API.Models.Role", b =>
                {
                    b.Property<int>("role_id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("role_active_default");

                    b.Property<string>("role_code");

                    b.Property<string>("role_description");

                    b.Property<DateTime>("role_system_date");

                    b.HasKey("role_id");

                    b.ToTable("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
